package com.zdmoney.credit.common.constant.system;

public enum SequencesEnum {
	
	MY_TEST("MY_TEST","SEQ_MY_TEST"),
	COM_EMPLOYEE("COM_EMPLOYEE","SEQ_COM_EMPLOYEE"),
	COM_EMPLOYEE_PERMISSION("COM_EMPLOYEE_PERMISSION","SEQ_COM_EMPLOYEE_PERMISSION"),
	COM_EMPLOYEE_ROLE("COM_EMPLOYEE_ROLE","SEQ_COM_EMPLOYEE_ROLE"),
	COM_ROLE_PERMISSION("COM_ROLE_PERMISSION","SEQ_COM_ROLE_PERMISSION"),
	SYS_OPERATION_LOG("SYS_OPERATION_LOG", "SEQ_SYS_OPERATION_LOG"),
	COM_ORGANIZATION("COM_ORGANIZATION","SEQ_COM_ORGANIZATION"),
	COM_ROLE("COM_ROLE","SEQ_COM_ROLE"),
	BASE_MESSAGE("BASE_MESSAGE","SEQ_BASE_MESSAGE"),//消息中心
	
	LOAN_RETURN("LOAN_RETURN","SEQ_LOAN_RETURN"),
	LOAN_RETURN_RECORD("LOAN_RETURN_RECORD","SEQ_LOAN_RETURN_RECORD"),
	
	BASE_REPAY_REMIND("BASE_REPAY_REMIND", "SEQ_BASE_REPAY_REMIND"),
	BASE_EMSSEND_INFO("BASE_EMSSEND_INFO", "SEQ_BASE_EMSSEND_INFO"),
	LOAN_LOG("LOAN_LOG","SEQ_LOAN_LOG"),
	SYS_ACTION_LOG("SYS_ACTION_LOG","SEQ_SYS_ACTION_LOG"),
	SYS_DICTIONARY("SYS_DICTIONARY","SEQ_SYS_DICTIONARY"),
	/** 借款人号码变更记录 **/
	PERSON_TEL_INFO("PERSON_TEL_INFO","SEQ_PERSON_TEL_INFO"),
	/** 借款人地址变更记录 **/
	PERSON_ADDRESS_INFO("PERSON_ADDRESS_INFO","SEQ_PERSON_ADDRESS_INFO"),
	/** 联系人信息 **/
	PERSON_CONTACT_INFO("PERSON_CONTACT_INFO","SEQ_PERSON_CONTACT_INFO"),
	
	LOAN_FILES_INFO("LOAN_FILES_INFO","SEQ_LOAN_FILES_INFO"),
	LOAN_COLLECTION_MANAGE_RECORD("LOAN_COLLECTION_MANAGE_RECORD","SEQ_LOAN_COLLECTION_MAN"),
	
	DEBIT_BASE_INFO("DEBIT_BASE_INFO","SEQ_DEBIT_BASE_INFO"),
	DEBIT_DETAIL_INFO("DEBIT_DETAIL_INFO","SEQ_DEBIT_DETAIL_INFO"),
	DEBIT_TRANSACTION("DEBIT_TRANSACTION","SEQ_DEBIT_TRANSACTION"),
	DEBIT_OFFER_FLOW("DEBIT_OFFER_FLOW","SEQ_DEBIT_OFFER_FLOW"),
	
	OFFER_INFO("OFFER_INFO","SEQ_OFFER_INFO"),
	OFFER_TRANSACTION("OFFER_TRANSACTION","SEQ_OFFER_TRANSACTION"),
	
	
	COM_MESSAGE_IN("COM_MESSAGE_IN","SEQ_COM_MESSAGE_IN"),

	PROD_CREDIT_PRODUCT_TERM("PROD_CREDIT_PRODUCT_TERM","SEQ_PROD_CREDIT_PRODUCT_TERM"),
	BASE_BATCH_INTERFACE_LOG("BASE_BATCH_INTERFACE_LOG", "SEQ_BASE_BATCH_LOG"),

	COM_MESSAGE_OUT("COM_MESSAGE_OUT","SEQ_COM_MESSAGE_OUT"),
	LOAN_MANAGE_SALES_DEP_LOG("LOAN_MANAGE_SALES_DEP_LOG","SEQ_LOAN_MANAGE_SALES_DEP_LOG"),
	BASE_PUBLIC_ACCOUNT_INFO("BASE_PUBLIC_ACCOUNT_INFO","SEQ_BASE_PUBLIC_ACCOUNT_INFO"),
	
	OFFER_REPAY_INFO("OFFER_REPAY_INFO","SEQ_OFFER_REPAY_INFO"),
	LOAN_ADVANCE_REPAYMENT("LOAN_ADVANCE_REPAYMENT", "SEQ_LOAN_ADVANCE_REPAYMENT"),
	COM_BLACKLIST("COM_BLACKLIST","SEQ_COM_BLACKLIST"),
	
	LOAN_TRUST_GRANT_INFO("LOAN_TRUST_GRANT_INFO","SEQ_LOAN_TRUST_GRANT_INFO"),
	OVERDUE_RATIO_STAT("OVERDUE_RATIO_STAT", "SEQ_OVERDUE_RATIO_STAT"),
	JIMU_EXT_REPAY("JIMU_EXT_REPAY", "SEQ_JIMU_EXT_REPAY"),
	JIMU_EXT_REPAY_ALL("JIMU_EXT_REPAY_ALL", "SEQ_JIMU_EXT_REPAY_ALL"),
	
	LOAN_PRE_SETTLE("LOAN_PRE_SETTLE", "SEQ_LOAN_PRE_SETTLE"),
	
	CONTRACT_NUMBER("CONTRACT_NUMBER", "SEQ_CONTRACT_NUMBER"),//生成合同编号专用，其他请勿用(业务专用)
	
	LOAN_BANK("LOAN_BANK", "SEQ_LOAN_BANK"),
	PERSON_INFO("PERSON_INFO", "SEQ_PERSON_INFO"),
	LOAN_BASE("LOAN_BASE", "SEQ_LOAN_BASE"),
	LOAN_INITIAL_INFO("LOAN_INITIAL_INFO", "SEQ_LOAN_INITIAL_INFO"),
	LOAN_PRODUCT("LOAN_PRODUCT", "SEQ_LOAN_PRODUCT"),
	FORTUNE_SURPORT("FORTUNE_SURPORT", "SEQ_FORTUNE_SURPORT"),
	PERSON_BANK_MAP("PERSON_BANK_MAP","SEQ_PERSON_BANK_MAP"),
	OFFER_FLOW("OFFER_FLOW", "SEQ_OFFER_FLOW"),

	LOAN_LEDGER("LOAN_LEDGER", "SEQ_LOAN_LEDGER"),
	LOAN_SPECIAL_REPAYMENT("LOAN_SPECIAL_REPAYMENT", "SEQ_LOAN_SPECIAL_REPAYMENT"),

	ZHONG_TAI("ZHONG_TAI", "SEQ_ZHONG_TAI"),
	XTJH("XTJH", "SEQ_XTJH"),
	PERSON_CAR_INFO("PERSON_CAR_INFO", "SEQ_PERSON_CAR_INFO"),
	PERSON_ENTREPRENEUR_INFO("PERSON_ENTREPRENEUR_INFO", "SEQ_PERSON_ENTREPRENEUR_INFO"),
	PERSON_HOUSE_INFO("PERSON_HOUSE_INFO", "SEQ_PERSON_HOUSE_INFO"),
	LOAN_REPAYMENT_DETAIL("LOAN_REPAYMENT_DETAIL", "SEQ_LOAN_REPAYMENT_DETAIL"),
	LOAN_CONTRACT("LOAN_CONTRACT", "SEQ_LOAN_CONTRACT"),
	CREDIT_USER_TPP("CREDIT_USER_TPP", "SEQ_CREDIT_USER_TPP"),
	DEBIT_ACCOUNT_INFO("DEBIT_ACCOUNT_INFO","SEQ_DEBIT_ACCOUNT_INFO"),
	
	LOAN_PROCESS_HISTORY("LOAN_PROCESS_HISTORY", "SEQ_LOAN_PROCESS_HISTORY"),
        
	PROD_CREDIT_PRODUCT_INFO("PROD_CREDIT_PRODUCT_INFO","SEQ_PROD_CREDIT_PRODUCT_INFO"),
	LOAN_BASE_BATCHNUM("LOAN_BASE","SEQ_LOAN_BATCH_NUM"),
	COM_ROLE_HIERARCHY("COM_EMPLOYEE_ROLE","SEQ_COM_ROLE_HIERARCHY"),
	PERSON_VISIT("PERSON_VISIT","SEQ_PERSON_VISIT"),
	PERSON_NFCS_WORKER_CALL("PERSON_NFCS_WORKER_CALL","SEQ_PERSON_NFCS_WORKER_CALL"),
	PERSON_THIRD_PARTY_ACCOUNT("PERSON_THIRD_PARTY_ACCOUNT", "SEQ_PERSON_THIRD_PARTY_ACCOUNT"),
	BASE_PRIVATE_ACCOUNT_INFO("BASE_PRIVATE_ACCOUNT_INFO","SEQ_BASE_PRIVATE_ACCOUNT_INFO"),
	OFFER_CONFIG("OFFER_CONFIG","SEQ_OFFER_CONFIG"),
	THIRD_LINE_OFFER("THIRD_LINE_OFFER","SEQ_THIRD_LINE_OFFER"),
	THIRD_LINE_OFFER_BATCH("THIRD_LINE_OFFER_BATCH","SEQ_THIRD_LINE_OFFER_BATCH"),
	THIRD_LINE_OFFER_TRANSACTION("THIRD_LINE_OFFER_TRANSACTION","SEQ_THIRD_LINE_OFFER_TRANSACT"),
	LOAN_THIRD_SOURCE_MEMO("LOAN_THIRD_SOURCE_MEMO", "SEQ_LOAN_THIRD_SOURCE_MEMO"),
	LOAN_FEE_INFO("LOAN_FEE_INFO", "SEQ_LOAN_FEE_INFO"),
	LOAN_FEE_OFFER("LOAN_FEE_OFFER", "SEQ_LOAN_FEE_OFFER"),
	LOAN_FEE_REPAY_INFO("LOAN_FEE_REPAY_INFO", "SEQ_LOAN_FEE_REPAY_INFO"),
	LOAN_FEE_TRANSACTION("LOAN_FEE_TRANSACTION", "SEQ_LOAN_FEE_TRANSACTION"),
	BASE_PUBLIC_ACCOUNT_INFO_WM("BASE_PUBLIC_ACCOUNT_INFO_WM","SEQ_BASE_PUBLIC_ACCOUNT_WM"),
	LOAN_FEE_IMPORT_DATA("LOAN_FEE_IMPORT_DATA", "SEQ_LOAN_FEE_IMPORT_DATA"),
	OFF_LINE_OFFER_BANK_DIC("OFF_LINE_OFFER_BANK_DIC", "SEQ_OFF_LINE_OFFER_BANK_DIC"),
	OFFER_EXPORT_RECORD("OFFER_EXPORT_RECORD", "SEQ_OFFER_EXPORT_RECORD"),
	LOAN_BANK_EXT("LOAN_BANK_EXT", "SEQ_LOAN_BANK_EXT"),
	LOAN_FEE_AMOUNT_CHANGE("LOAN_FEE_AMOUNT_CHANGE", "SEQ_LOAN_FEE_AMOUNT_CHANGE"),
	OFFER_EXPORT_BATCH("OFFER_EXPORT_BATCH","SEQ_OFFER_EXPORT_BATCH"),
	UPLOAD_FTP_FILE_LOG("UPLOAD_FTP_FILE_LOG","SEQ_UPLOAD_FTP_FILE_LOG"),
	UPLOAD_LOAN_DATA_INFO("UPLOAD_LOAN_DATA_INFO","SEQ_UPLOAD_LOAN_DATA_INFO"),
	REQUEST_FILE_OPERATE_RECORD("REQUEST_FILE_OPERATE_RECORD","SEQ_REQUEST_FILE_OPER_RECORD"),
	OFFER_FEE_FLOW("OFFER_FEE_FLOW","SEQ_OFFER_FEE_FLOW"),
	LOAN_FEE_REPAY_RECORD("LOAN_FEE_REPAY_RECORD","SEQ_LOAN_FEE_REPAY_RECORD"),
	OFFER_CHANNEL("OFFER_CHANNEL","SEQ_OFFER_CHANNEL"),
	TRUST_OFFER_FLOW("TRUST_OFFER_FLOW","SEQ_TRUST_OFFER_FLOW"),
	APP_NOTICE("APP_NOTICE", "SEQ_APP_NOTICE"),
	LOAN_BASE_GRANT("LOAN_BASE_GRANT", "SEQ_LOAN_BASE_GRANT"),
	LOAN_BASE_ALL_REPAYMENT("LOAN_BASE_ALL_REPAYMENT","SEQ_LOAN_BASE_ALL_REPAYMENT"),
	ABS_DEDUCT_RESULT_UPLOAD("ABS_DEDUCT_RESULT_UPLOAD","SEQ_ABS_DEDUCT_RESULT"),
	ABS_FEE_REDUCE_APPLY("ABS_FEE_REDUCE_APPLY","SEQ_ABS_FEE_REDUCE_APPLY"),
	ELECTRONIC_SIGNATURE_LOG("ELECTRONIC_SIGNATURE_LOG","SEQ_ELECTRONIC_SIGNATURE_LOG"),
	APPLY_BOOK_INFO("APPLY_BOOK_INFO","SEQ_APPLY_BOOK_INFO"),
	LOAN_BSB_MAPPING("LOAN_BSB_MAPPING", "SEQ_LOAN_BSB_MAPPING"),
	REPAY_RESULT_NOTIFY_LOG("REPAY_RESULT_NOTIFY_LOG", "SEQ_REPAY_RESULT_NOTIFY_LOG"),
	REPAY_BUS_LOG("REPAY_BUS_LOG", "SEQ_REPAY_BUS_LOG"),
	EARLY_REPAY_CALCULATE("EARLY_REPAY_CALCULATE", "SEQ_EARLY_REPAY_CALCULATE"),
	GRANT_REC_DETAIL("GRANT_REC_DETAIL", "SEQ_GRANT_REC_DETAIL"),
	REPAY_REC_DETAIL("REPAY_REC_DETAIL", "SEQ_REPAY_REC_DETAIL"),
	OPERATE_LOG("OPERATE_LOG","SEQ_OPERATE_LOG"),
	DEBIT_OFFLINE_OFFER_INFO("DEBIT_OFFLINE_OFFER_INFO","SEQ_DEBIT_OFFLINE_OFFER_INFO"),
	OFFLINE_REPAY_RELATION("OFFLINE_REPAY_RELATION","SEQ_OFFLINE_REPAY_RELATION"),
	PUBLIC_ACCOUNT_DETAIL("PUBLIC_ACCOUNT_DETAIL","SEQ_PUBLIC_ACCOUNT_DETAIL"),
	DEBIT_QUEUE_LOG("DEBIT_QUEUE_LOG","SEQ_DEBIT_QUEUE_LOG"),
	SPLIT_QUEUE_LOG("SPLIT_QUEUE_LOG","SEQ_SPLIT_QUEUE_LOG"),
	LOAN_REPAYMENT_DETAIL_LUFAX("LOAN_REPAYMENT_DETAIL_LUFAX","SEQ_LOAN_REPAYMENT_DETAIL_LU"),
	UPLOAD_LOAN_PROTOCOL_LOG("UPLOAD_LOAN_PROTOCOL_LOG","SEQ_UPLOAD_LOAN_PROTOCOL_LOG"),
	UPLOAD_HKQR_BOOK_LOG("UPLOAD_HKQR_BOOK_LOG","SEQ_UPLOAD_HKQR_BOOK_LOG"),
	LOAN_STATUS_LUFAX("LOAN_STATUS_LUFAX","SEQ_LOAN_STATUS_LUFAX"),
	COMPENSATORY_DETAIL_LUFAX("COMPENSATORY_DETAIL_LUFAX","SEQ_COMPENSATORY_DETAIL_LUFAX"),
	COM_ORG_TYPE("COM_ORG_TYPE","SEQ_COM_ORG_TYPE"),
	SPECIAL_REPAYMENT_RELATION("SPECIAL_REPAYMENT_RELATION","SEQ_SPECIAL_REPAYMENT_RELATION"),
	SPECIAL_REPAYMENT_APPLY("SPECIAL_REPAYMENT_APPLY","SEQ_SPECIAL_REPAYMENT_APPLY"),
	SPECIAL_TRADE_RELATION("SPECIAL_TRADE_RELATION","SEQ_SPECIAL_TRADE_RELATION"),
	LOAN_OFFER_INFO("LOAN_OFFER_INFO","SEQ_LOAN_OFFER_INFO"),
	LOAN_FEE_OFFER_QUEUE("LOAN_FEE_OFFER_QUEUE","SEQ_LOAN_FEE_OFFER_QUEUE"),
	SP_FLOW_INSTANCE("SP_FLOW_INSTANCE","SEQ_SP_FLOW_INSTANCE"),
	SP_FLOW_TRANSITION_INFO("SP_FLOW_TRANSITION_INFO","SEQ_SP_FLOW_TRANSITION_INFO"),
	SP_NODE_EMPLOYEE("SP_NODE_EMPLOYEE","SEQ_SP_NODE_EMPLOYEE"),
	RISK_AMOUNT_DETAIL("RISK_AMOUNT_DETAIL","SEQ_RISK_AMOUNT_DETAIL"),
	LOAN_PRE_APPLY_RECORD("LOAN_PRE_APPLY_RECORD","SEQ_LOAN_PRE_APPLY_RECORD"),
	LOAN_TRANSFER_INFO("LOAN_TRANSFER_INFO","SEQ_LOAN_TRANSFER_INFO"),
	LOAN_INFO_EXT("LOAN_INFO_EXT","SEQ_LOAN_INFO_EXT"),
	LOAN_EVALUATE_INFO("LOAN_EVALUATE_INFO","SEQ_LOAN_EVALUATE_INFO"),
	PAY_CHANNEL("PAY_CHANNEL","SEQ_PAY_CHANNEL"),
	LOAN_REPAYMENT_STATE("LOAN_REPAYMENT_STATE","SEQ_LOAN_REPAYMENT_STATE"),
	LOAN_SETTLE_INFO("LOAN_SETTLE_INFO","SEQ_LOAN_SETTLE_INFO");
	/** 表名 **/	
	private String tableName;
	/** 序列名**/
	private String sequencesName;
	
	SequencesEnum(String tableName,String sequencesName) {
		this.tableName = tableName;
		this.sequencesName = sequencesName;
	}

	public String getTableName() {
		return tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	public String getSequencesName() {
		return sequencesName;
	}

	public void setSequencesName(String sequencesName) {
		this.sequencesName = sequencesName;
	}
	
}
