package com.zdmoney.credit.blackList.service;


import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

import com.zdmoney.credit.blackList.service.pub.RiskControlServiceSoap;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * RiskControlService service = new RiskControlService();
 * RiskControlServiceSoap portType = service.getRiskControlServiceSoap();
 * portType.addCustomerBlackListXml(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "RiskControlService", targetNamespace = "http://www.zendai.com/", wsdlLocation = "http://114.80.110.32:8119/RiskControlService.asmx?WSDL")
public class RiskControlService extends Service {

	private final static URL RISKCONTROLSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(RiskControlService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = RiskControlService.class.getResource(".");
			url = new URL(baseUrl,
					"http://114.80.110.32:8119/RiskControlService.asmx?WSDL");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://114.80.110.32:8119/RiskControlService.asmx?WSDL', retrying as a local file");
			logger.warning(e.getMessage());
		}
		RISKCONTROLSERVICE_WSDL_LOCATION = url;
	}

	public RiskControlService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public RiskControlService() {
		super(RISKCONTROLSERVICE_WSDL_LOCATION, new QName(
				"http://www.zendai.com/", "RiskControlService"));
	}

	/**
	 * 
	 * @return returns RiskControlServiceSoap
	 */
	@WebEndpoint(name = "RiskControlServiceSoap")
	public RiskControlServiceSoap getRiskControlServiceSoap() {
		return super.getPort(new QName("http://www.zendai.com/",
				"RiskControlServiceSoap"), RiskControlServiceSoap.class);
	}

	/**
	 * 
	 * @return returns RiskControlServiceSoap
	 */
	@WebEndpoint(name = "RiskControlServiceSoap12")
	public RiskControlServiceSoap getRiskControlServiceSoap12() {
		return super.getPort(new QName("http://www.zendai.com/",
				"RiskControlServiceSoap12"), RiskControlServiceSoap.class);
	}

}
